get:
  tags:
    - Products
  summary: "List all products"
  description: "List all products."
  operationId: listProducts
  responses:
    '200':
      description: "Success"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../components/schemas/v1/product_list.yaml'
    '401':
      description: "Unauthorized"
    '403':
      description: "Forbidden"
    '404':
      description: "Not found"
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/Problem.yaml'
    '500':
      description: "Internal server error"
