get:
  tags:
    - Customer
  summary: "Get a product"
  description: "Get a product by ID."
  operationId: getProductById
  parameters:
    - name: productId
      in: path
      description: "The ID of the product to retrieve."
      required: true
      schema:
        type: string
        format: uuid
  responses:
    '200':
      description: "Success"
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/customer.yaml'
    '400':
      description: "Bad request"
    '401':
      description: "Unauthorized"
    '403':
      description: "Forbidden"
    '404':
      description: "Not found"
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/Problem.yaml'
    '500':
      description: "Internal server error"

